spigot:
  container_name: lbryquest
  build: .
  volumes:
    - "./target/lbryquest.jar:/spigot/plugins/lbryquest.jar"
  ports:
    - "25565:25565"
  environment:
    - LBRYQUEST_ENV=production
      - LBRYQUEST_NODE_USERNAME=lbry
      - LBRYQUEST_NODE_PASSWORD=lbry
      - LBRYQUEST_NODE_HOST=127.0.0.1
      - ADMIN_UUID=5677c824-da7e-3d3d-862a-88db1ea91a61
      - POSTGRES_PORT_5432_TCP_PORT=5432

  links:
    - redis
redis:
  image: redis

