superuser: null
# commented until <walletAmount> gets a class getter
welcomeMessage:
   <bold><yellow>Welcome to LBRY Quest, the server that runs on LBRY Credits! ^_^<reset>

   <yellow>Your LBRY Quest address is <green><walletAddress>
   <yellow>Your balance is <green><walletAmount> SAT